name = "vectormatevless"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "172.232.239.134,587,ID,Akamai Technologies  Inc"
UUID = "cfc23864-7f5b-4d38-8214-ecd93767ecd8"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
